### ISSUE TITLE
run "sudo luarocks install luasoap" got a error

### ISSUE THREAD

**Issue by csufangyu** [tomasguisasola/luasoap#16]
Hi,tanks for your good job.I try to install luasoap,but I get a error,the error is:
`sudo luarocks install luasoap
Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...
Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec... switching to 'build' mode

Missing dependencies for luasoap:
http-digest >= 1.2.2-1

Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock... switching to 'build' mode

Missing dependencies for http-digest:
md5 

Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching to 'build' mode

Error: Failed installing dependency: https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec - Error fetching file: Failed downloading https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert protocol version
`
wolud you help me?thanks very much!

**Comment by tomasguisasola** [comment]
Hi

The error message says "Failed downloading
https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it seems you
had a temporary failure, don't you?  I just checked out this URL and the
file could be successfully downloaded.  Besides, there is a following
message "tlsv1 alert protocol version" that I have never seen.  I don't
know if this is some kind of configuration you have...  I recommend you
check this out too.  But let me know if the problem is solved!

Regards,
Tomás

Em seg., 20 de abr. de 2020 às 04:00, universe <notifications@github.com>
escreveu:
>
> Hi,tanks for your good job.I try to install luasoap,but I get a error,the
error is:
> `sudo luarocks install luasoap
> Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...
> Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec... switching
to 'build' mode
>
> Missing dependencies for luasoap:
> http-digest >= 1.2.2-1
>
> Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...
switching to 'build' mode
>
> Missing dependencies for http-digest:
> md5
>
> Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching to
'build' mode
>
> Error: Failed installing dependency:
https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed
installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec -
Error fetching file: Failed downloading
https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert
protocol version

**Comment by csufangyu** [comment]
ok！and I guess it may be caused by the network!becase when I try to visit the website, he will remind me that the connection is not secure.and I got a new error,it is:
sudo ./build 
[sudo] password for robot: 


Building "lua" files: "/home/robot/Robot_Project/drakon.tech/app"
Minifying Javascript files
ContextMenu.js... couldn't execute "java": no such file or directory
    while executing
"exec java -jar $closdir/compiler.jar --js_output_file=$outdir/$file_only $file"
    ("foreach" body line 6)
    invoked from within
"foreach file $jsfiles {
set file_only [ file tail $file ]
if {$file_only != "loader.js"} {
puts -nonewline "$file_only... "
flush stdout
set r..."
    (file "./build" line 104)
 and I guess it may be caused   by Java.thanks!










At 2020-04-20 20:14:22, "Tomás Guisasola" <notifications@github.com> wrote:

Hi

The error message says "Failed downloading
https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it seems you
had a temporary failure, don't you? I just checked out this URL and the
file could be successfully downloaded. Besides, there is a following
message "tlsv1 alert protocol version" that I have never seen. I don't
know if this is some kind of configuration you have... I recommend you
check this out too. But let me know if the problem is solved!

Regards,
Tomás

Em seg., 20 de abr. de 2020 às 04:00, universe <notifications@github.com>
escreveu:
>
> Hi,tanks for your good job.I try to install luasoap,but I get a error,the
error is:
> `sudo luarocks install luasoap
> Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...
> Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec... switching
to 'build' mode
>
> Missing dependencies for luasoap:
> http-digest >= 1.2.2-1
>
> Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...
switching to 'build' mode
>
> Missing dependencies for http-digest:
> md5
>
> Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching to
'build' mode
>
> Error: Failed installing dependency:
https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed
installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec -
Error fetching file: Failed downloading
https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert
protocol version

**Comment by csufangyu** [comment]
Hi，I've been able to compile now, but I'm still having problems when I run it, I suspect it's a path dependency issue, it's a problem with "HtmlUtils.js". I would like to ask you if you have encountered this type of problem while testing locally?thanks very much！-------- 原始邮件 --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月20日周一 晚上8:14收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <csufangyu@163.com>, Author <author@noreply.github.com>主    题： Re: [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error (#16)

Hi



The error message says "Failed downloading

https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it seems you

had a temporary failure, don't you?  I just checked out this URL and the

file could be successfully downloaded.  Besides, there is a following

message "tlsv1 alert protocol version" that I have never seen.  I don't

know if this is some kind of configuration you have...  I recommend you

check this out too.  But let me know if the problem is solved!



Regards,

Tomás



Em seg., 20 de abr. de 2020 às 04:00, universe <notifications@github.com>

escreveu:

>

> Hi,tanks for your good job.I try to install luasoap,but I get a error,the

error is:

> `sudo luarocks install luasoap

> Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...

> Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec... switching

to 'build' mode

>

> Missing dependencies for luasoap:

> http-digest >= 1.2.2-1

>

> Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...

switching to 'build' mode

>

> Missing dependencies for http-digest:

> md5

>

> Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching to

'build' mode

>

> Error: Failed installing dependency:

https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed

installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec -

Error fetching file: Failed downloading

https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert

protocol version

**Comment by tomasguisasola** [comment]
Hi

I couldn't find any file called HtmlUtils.js nor anything similar.  Are you
sure the problem  is with that file?  What are the error messages?  I have
not encountered this type of problem...

Regards,
Tomás

Em dom., 26 de abr. de 2020 às 23:15, universe <notifications@github.com>
escreveu:
>
> Hi，I've been able to compile now, but I'm still having problems when I
run it, I suspect it's a path dependency issue, it's a problem with
"HtmlUtils.js". I would like to ask you if you have encountered this type
of problem while testing locally?thanks very much！-------- 原始邮件
--------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月20日周一
晚上8:14收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <
csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:
[tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error
(#16)
> Hi
>
> The error message says "Failed downloading
> https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it seems
you
> had a temporary failure, don't you? I just checked out this URL and the
> file could be successfully downloaded. Besides, there is a following
> message "tlsv1 alert protocol version" that I have never seen. I don't
> know if this is some kind of configuration you have... I recommend you
> check this out too. But let me know if the problem is solved!
>
> Regards,
> Tomás
>
> Em seg., 20 de abr. de 2020 às 04:00, universe <notifications@github.com>
> escreveu:
> >
> > Hi,tanks for your good job.I try to install luasoap,but I get a
error,the
> error is:
> > `sudo luarocks install luasoap
> > Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...
> > Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec... switching
> to 'build' mode
> >
> > Missing dependencies for luasoap:
> > http-digest >= 1.2.2-1
> >
> > Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...
> switching to 'build' mode
> >
> > Missing dependencies for http-digest:
> > md5
> >
> > Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching to
> 'build' mode
> >
> > Error: Failed installing dependency:
> https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed
> installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec -
> Error fetching file: Failed downloading
> https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert
> protocol version
> > `
> > wolud you help me?thanks very much!
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
>
>
> —You are receiving this because you authored the thread.Reply to this
email directly, view it on GitHub, or unsubscribe.

**Comment by csufangyu** [comment]
Maybe I don't have Script/deploy，and I just use deploy in drackhub. could you give me the Script flies ? and I don't use the compiler.-------- 原始邮件 --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月27日周一 晚上7:41收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <csufangyu@163.com>, Author <author@noreply.github.com>主    题： Re: [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error (#16)

Hi



I couldn't find any file called HtmlUtils.js nor anything similar.  Are you

sure the problem  is with that file?  What are the error messages?  I have

not encountered this type of problem...



Regards,

Tomás



Em dom., 26 de abr. de 2020 às 23:15, universe <notifications@github.com>

escreveu:

>

> Hi，I've been able to compile now, but I'm still having problems when I

run it, I suspect it's a path dependency issue, it's a problem with

"HtmlUtils.js". I would like to ask you if you have encountered this type

of problem while testing locally?thanks very much！-------- 原始邮件

--------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月20日周一

晚上8:14收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <

csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:

[tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error

(#16)

> Hi

>

> The error message says "Failed downloading

> https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it seems

you

> had a temporary failure, don't you? I just checked out this URL and the

> file could be successfully downloaded. Besides, there is a following

> message "tlsv1 alert protocol version" that I have never seen. I don't

> know if this is some kind of configuration you have... I recommend you

> check this out too. But let me know if the problem is solved!

>

> Regards,

> Tomás

>

> Em seg., 20 de abr. de 2020 às 04:00, universe <notifications@github.com>

> escreveu:

> >

> > Hi,tanks for your good job.I try to install luasoap,but I get a

error,the

> error is:

> > `sudo luarocks install luasoap

> > Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...

> > Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec... switching

> to 'build' mode

> >

> > Missing dependencies for luasoap:

> > http-digest >= 1.2.2-1

> >

> > Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...

> switching to 'build' mode

> >

> > Missing dependencies for http-digest:

> > md5

> >

> > Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching to

> 'build' mode

> >

> > Error: Failed installing dependency:

> https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed

> installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec -

> Error fetching file: Failed downloading

> https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert

> protocol version

> > `

> > wolud you help me?thanks very much!

> >

> > —

> > You are receiving this because you are subscribed to this thread.

> > Reply to this email directly, view it on GitHub, or unsubscribe.

>

>

> —You are receiving this because you authored the thread.Reply to this

email directly, view it on GitHub, or unsubscribe.

**Comment by tomasguisasola** [comment]
Hi

I could not understand what you are asking.  What are the "Script files"?

Regards,
Tomás

Em seg., 27 de abr. de 2020 às 23:22, universe <notifications@github.com>
escreveu:
>
> Maybe I don't have Script/deploy，and I just use deploy in drackhub. could
you give me the Script flies ? and I don't use the compiler.-------- 原始邮件
--------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月27日周一
晚上7:41收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <
csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:
[tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error
(#16)
> Hi
>
> I couldn't find any file called HtmlUtils.js nor anything similar. Are you
> sure the problem is with that file? What are the error messages? I have
> not encountered this type of problem...
>
> Regards,
> Tomás
>
> Em dom., 26 de abr. de 2020 às 23:15, universe <notifications@github.com>
> escreveu:
> >
> > Hi，I've been able to compile now, but I'm still having problems when I
> run it, I suspect it's a path dependency issue, it's a problem with
> "HtmlUtils.js". I would like to ask you if you have encountered this type
> of problem while testing locally?thanks very much！-------- 原始邮件
> --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月20日周一
> 晚上8:14收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送：
universe <
> csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:
> [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error
> (#16)
> > Hi
> >
> > The error message says "Failed downloading
> > https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it seems
> you
> > had a temporary failure, don't you? I just checked out this URL and the
> > file could be successfully downloaded. Besides, there is a following
> > message "tlsv1 alert protocol version" that I have never seen. I don't
> > know if this is some kind of configuration you have... I recommend you
> > check this out too. But let me know if the problem is solved!
> >
> > Regards,
> > Tomás
> >
> > Em seg., 20 de abr. de 2020 às 04:00, universe <notifications@github.com
>
> > escreveu:
> > >
> > > Hi,tanks for your good job.I try to install luasoap,but I get a
> error,the
> > error is:
> > > `sudo luarocks install luasoap
> > > Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...
> > > Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...
switching
> > to 'build' mode
> > >
> > > Missing dependencies for luasoap:
> > > http-digest >= 1.2.2-1
> > >
> > > Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...
> > switching to 'build' mode
> > >
> > > Missing dependencies for http-digest:
> > > md5
> > >
> > > Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching to
> > 'build' mode
> > >
> > > Error: Failed installing dependency:
> > https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed
> > installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec -
> > Error fetching file: Failed downloading
> > https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert
> > protocol version
> > > `
> > > wolud you help me?thanks very much!
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> >
> >
> > —You are receiving this because you authored the thread.Reply to this
> email directly, view it on GitHub, or unsubscribe.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
>
>
> —You are receiving this because you authored the thread.Reply to this
email directly, view it on GitHub, or unsubscribe.

**Comment by csufangyu** [comment]
in the docs/on premises. txt，the line 110，it writes “copy the scripts/deploy to the server”，and the line 112 sudo  ./deploy 201811110836. zip.  I can't find the scripts，so I use the drakonhub. . -------- 原始邮件 --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月28日周二 晚上7:13收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <csufangyu@163.com>, Author <author@noreply.github.com>主    题： Re: [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error (#16)

Hi



I could not understand what you are asking.  What are the "Script files"?



Regards,

Tomás



Em seg., 27 de abr. de 2020 às 23:22, universe <notifications@github.com>

escreveu:

>

> Maybe I don't have Script/deploy，and I just use deploy in drackhub. could

you give me the Script flies ? and I don't use the compiler.-------- 原始邮件

--------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月27日周一

晚上7:41收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <

csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:

[tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error

(#16)

> Hi

>

> I couldn't find any file called HtmlUtils.js nor anything similar. Are you

> sure the problem is with that file? What are the error messages? I have

> not encountered this type of problem...

>

> Regards,

> Tomás

>

> Em dom., 26 de abr. de 2020 às 23:15, universe <notifications@github.com>

> escreveu:

> >

> > Hi，I've been able to compile now, but I'm still having problems when I

> run it, I suspect it's a path dependency issue, it's a problem with

> "HtmlUtils.js". I would like to ask you if you have encountered this type

> of problem while testing locally?thanks very much！-------- 原始邮件

> --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月20日周一

> 晚上8:14收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送：

universe <

> csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:

> [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error

> (#16)

> > Hi

> >

> > The error message says "Failed downloading

> > https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it seems

> you

> > had a temporary failure, don't you? I just checked out this URL and the

> > file could be successfully downloaded. Besides, there is a following

> > message "tlsv1 alert protocol version" that I have never seen. I don't

> > know if this is some kind of configuration you have... I recommend you

> > check this out too. But let me know if the problem is solved!

> >

> > Regards,

> > Tomás

> >

> > Em seg., 20 de abr. de 2020 às 04:00, universe <notifications@github.com

>

> > escreveu:

> > >

> > > Hi,tanks for your good job.I try to install luasoap,but I get a

> error,the

> > error is:

> > > `sudo luarocks install luasoap

> > > Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...

> > > Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...

switching

> > to 'build' mode

> > >

> > > Missing dependencies for luasoap:

> > > http-digest >= 1.2.2-1

> > >

> > > Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...

> > switching to 'build' mode

> > >

> > > Missing dependencies for http-digest:

> > > md5

> > >

> > > Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching to

> > 'build' mode

> > >

> > > Error: Failed installing dependency:

> > https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed

> > installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec -

> > Error fetching file: Failed downloading

> > https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert

> > protocol version

> > > `

> > > wolud you help me?thanks very much!

> > >

> > > —

> > > You are receiving this because you are subscribed to this thread.

> > > Reply to this email directly, view it on GitHub, or unsubscribe.

> >

> >

> > —You are receiving this because you authored the thread.Reply to this

> email directly, view it on GitHub, or unsubscribe.

> >

> > —

> > You are receiving this because you commented.

> > Reply to this email directly, view it on GitHub, or unsubscribe.

>

>

> —You are receiving this because you authored the thread.Reply to this

email directly, view it on GitHub, or unsubscribe.

**Comment by tomasguisasola** [comment]
Hi

Sorry, but there is no such file "premises.txt" in LuaSOAP (not in the
distribution nor in the .rock nor even in the git repo).  I think you are
mixing it with other software.  Maybe you are installing some other
software that depends on LuaSOAP...

Regards,
Tomás

Em ter., 28 de abr. de 2020 às 08:59, universe <notifications@github.com>
escreveu:
>
> in the docs/on premises. txt，the line 110，it writes “copy the
scripts/deploy to the server”，and the line 112 sudo ./deploy 201811110836.
zip. I can't find the scripts，so I use the drakonhub. . -------- 原始邮件
--------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月28日周二
晚上7:13收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <
csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:
[tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error
(#16)
> Hi
>
> I could not understand what you are asking. What are the "Script files"?
>
> Regards,
> Tomás
>
> Em seg., 27 de abr. de 2020 às 23:22, universe <notifications@github.com>
> escreveu:
> >
> > Maybe I don't have Script/deploy，and I just use deploy in drackhub.
could
> you give me the Script flies ? and I don't use the compiler.-------- 原始邮件
> --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月27日周一
> 晚上7:41收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送：
universe <
> csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:
> [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error
> (#16)
> > Hi
> >
> > I couldn't find any file called HtmlUtils.js nor anything similar. Are
you
> > sure the problem is with that file? What are the error messages? I have
> > not encountered this type of problem...
> >
> > Regards,
> > Tomás
> >
> > Em dom., 26 de abr. de 2020 às 23:15, universe <notifications@github.com
>
> > escreveu:
> > >
> > > Hi，I've been able to compile now, but I'm still having problems when I
> > run it, I suspect it's a path dependency issue, it's a problem with
> > "HtmlUtils.js". I would like to ask you if you have encountered this
type
> > of problem while testing locally?thanks very much！-------- 原始邮件
> > --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月20日周一
> > 晚上8:14收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送：
> universe <
> > csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:
> > [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error
> > (#16)
> > > Hi
> > >
> > > The error message says "Failed downloading
> > > https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it
seems
> > you
> > > had a temporary failure, don't you? I just checked out this URL and
the
> > > file could be successfully downloaded. Besides, there is a following
> > > message "tlsv1 alert protocol version" that I have never seen. I don't
> > > know if this is some kind of configuration you have... I recommend you
> > > check this out too. But let me know if the problem is solved!
> > >
> > > Regards,
> > > Tomás
> > >
> > > Em seg., 20 de abr. de 2020 às 04:00, universe <
notifications@github.com
> >
> > > escreveu:
> > > >
> > > > Hi,tanks for your good job.I try to install luasoap,but I get a
> > error,the
> > > error is:
> > > > `sudo luarocks install luasoap
> > > > Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...
> > > > Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...
> switching
> > > to 'build' mode
> > > >
> > > > Missing dependencies for luasoap:
> > > > http-digest >= 1.2.2-1
> > > >
> > > > Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...
> > > switching to 'build' mode
> > > >
> > > > Missing dependencies for http-digest:
> > > > md5
> > > >
> > > > Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching
to
> > > 'build' mode
> > > >
> > > > Error: Failed installing dependency:
> > > https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed
> > > installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec
-
> > > Error fetching file: Failed downloading
> > > https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert
> > > protocol version
> > > > `
> > > > wolud you help me?thanks very much!
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly, view it on GitHub, or unsubscribe.
> > >
> > >
> > > —You are receiving this because you authored the thread.Reply to this
> > email directly, view it on GitHub, or unsubscribe.
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> >
> >
> > —You are receiving this because you authored the thread.Reply to this
> email directly, view it on GitHub, or unsubscribe.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
>
>
> —You are receiving this because you authored the thread.Reply to this
email directly, view it on GitHub, or unsubscribe.

**Comment by csufangyu** [comment]
oh i am so sorry!because these days  I have too much things to do! I am so sorry!thanks very much!-------- 原始邮件 --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月28日周二 晚上8:21收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <csufangyu@163.com>, Author <author@noreply.github.com>主    题： Re: [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error (#16)

Hi



Sorry, but there is no such file "premises.txt" in LuaSOAP (not in the

distribution nor in the .rock nor even in the git repo).  I think you are

mixing it with other software.  Maybe you are installing some other

software that depends on LuaSOAP...



Regards,

Tomás



Em ter., 28 de abr. de 2020 às 08:59, universe <notifications@github.com>

escreveu:

>

> in the docs/on premises. txt，the line 110，it writes “copy the

scripts/deploy to the server”，and the line 112 sudo ./deploy 201811110836.

zip. I can't find the scripts，so I use the drakonhub. . -------- 原始邮件

--------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月28日周二

晚上7:13收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送： universe <

csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:

[tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error

(#16)

> Hi

>

> I could not understand what you are asking. What are the "Script files"?

>

> Regards,

> Tomás

>

> Em seg., 27 de abr. de 2020 às 23:22, universe <notifications@github.com>

> escreveu:

> >

> > Maybe I don't have Script/deploy，and I just use deploy in drackhub.

could

> you give me the Script flies ? and I don't use the compiler.-------- 原始邮件

> --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月27日周一

> 晚上7:41收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送：

universe <

> csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:

> [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error

> (#16)

> > Hi

> >

> > I couldn't find any file called HtmlUtils.js nor anything similar. Are

you

> > sure the problem is with that file? What are the error messages? I have

> > not encountered this type of problem...

> >

> > Regards,

> > Tomás

> >

> > Em dom., 26 de abr. de 2020 às 23:15, universe <notifications@github.com

>

> > escreveu:

> > >

> > > Hi，I've been able to compile now, but I'm still having problems when I

> > run it, I suspect it's a path dependency issue, it's a problem with

> > "HtmlUtils.js". I would like to ask you if you have encountered this

type

> > of problem while testing locally?thanks very much！-------- 原始邮件

> > --------发件人： Tomás Guisasola <notifications@github.com>日期： 2020年4月20日周一

> > 晚上8:14收件人： tomasguisasola/luasoap <luasoap@noreply.github.com>抄送：

> universe <

> > csufangyu@163.com>, Author <author@noreply.github.com>主 题： Re:

> > [tomasguisasola/luasoap] run "sudo luarocks install luasoap" got a error

> > (#16)

> > > Hi

> > >

> > > The error message says "Failed downloading

> > > https://github.com/keplerproject/md5/archive/1.3.tar.gz", thus it

seems

> > you

> > > had a temporary failure, don't you? I just checked out this URL and

the

> > > file could be successfully downloaded. Besides, there is a following

> > > message "tlsv1 alert protocol version" that I have never seen. I don't

> > > know if this is some kind of configuration you have... I recommend you

> > > check this out too. But let me know if the problem is solved!

> > >

> > > Regards,

> > > Tomás

> > >

> > > Em seg., 20 de abr. de 2020 às 04:00, universe <

notifications@github.com

> >

> > > escreveu:

> > > >

> > > > Hi,tanks for your good job.I try to install luasoap,but I get a

> > error,the

> > > error is:

> > > > `sudo luarocks install luasoap

> > > > Installing https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...

> > > > Using https://rocks.moonscript.org/luasoap-4.0.1-1.rockspec...

> switching

> > > to 'build' mode

> > > >

> > > > Missing dependencies for luasoap:

> > > > http-digest >= 1.2.2-1

> > > >

> > > > Using https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock...

> > > switching to 'build' mode

> > > >

> > > > Missing dependencies for http-digest:

> > > > md5

> > > >

> > > > Using https://rocks.moonscript.org/md5-1.3-1.rockspec... switching

to

> > > 'build' mode

> > > >

> > > > Error: Failed installing dependency:

> > > https://rocks.moonscript.org/http-digest-1.2.2-1.src.rock - Failed

> > > installing dependency: https://rocks.moonscript.org/md5-1.3-1.rockspec

-

> > > Error fetching file: Failed downloading

> > > https://github.com/keplerproject/md5/archive/1.3.tar.gz - tlsv1 alert

> > > protocol version

> > > > `

> > > > wolud you help me?thanks very much!

> > > >

> > > > —

> > > > You are receiving this because you are subscribed to this thread.

> > > > Reply to this email directly, view it on GitHub, or unsubscribe.

> > >

> > >

> > > —You are receiving this because you authored the thread.Reply to this

> > email directly, view it on GitHub, or unsubscribe.

> > >

> > > —

> > > You are receiving this because you commented.

> > > Reply to this email directly, view it on GitHub, or unsubscribe.

> >

> >

> > —You are receiving this because you authored the thread.Reply to this

> email directly, view it on GitHub, or unsubscribe.

> >

> > —

> > You are receiving this because you commented.

> > Reply to this email directly, view it on GitHub, or unsubscribe.

>

>

> —You are receiving this because you authored the thread.Reply to this

email directly, view it on GitHub, or unsubscribe.
