### ISSUE TITLE
Bugs in response processing

### ISSUE THREAD

**Issue by fpaquet** [tomasguisasola/luasoap#4]
We found 3 issues with luasoap 3.0 (latest)
1. list_children() fails to access the second and any further elements
   error: soap.lua:215: attempt to index global 'self' (a nil value)
2. some webservices omit the SOAP-ENV:Header
    if SOAP-ENV:Header is missing, decode() will fail to locate the SOAP-ENV:Body
3. decode() fails to return any response entries
   error: soap.lua:~251: attempt to index local 'obj' (a function value)
4. because a response contains lots of whitespace entries, we suggest
   that you add something like list_children() to the public interface of soap

**Comment by denisdemais** [comment]
@fpaquet do you can attach the soap reply (raw) with optional header ?

**Comment by fpaquet** [comment]
Hello Denis

I'm not sure wether i can reproduce today the SOAP reply that we got in 2012.
(the SOAP services have changed in the meantime) 

LuaSOAP is running absolutely fine with the patch since several years now.

The patch fixes 3 errors while retaining 100% compatibility with previous behaviour.
Why not merge it into master and check LuaSOAP ist still working today?
