### ISSUE TITLE
xml/network api neutral

### ISSUE THREAD

**Issue by denisdemais** [tomasguisasola/luasoap#9]
Hi.

Defacto luasocket is the most used network api, but, if possible do you can be adapt to works with any API (signature/error codes / layers / aka c function pointers) - the user can be responsible to implement. In same way xml library.

i.e.,
lsocket -> http://tset.de/lsocket/index.html
luacurl -> http://luacurl.luaforge.net/
luaposix -> https://github.com/luaposix/luaposix
and many others

in same way assembley the xml soap/envelope, p. ex., implementations with support to attributes in pure lua or binding.

luasocket x.y + luasec 0.x = problematic ;)

**Comment by tomasguisasola** [comment]
Hi Denis

I think it is not difficult to adapt LuaSOAP to use other libraries, but 
now I am a bit busy :-(

I'll take a look at ghttplib but I couldn't find a bind to Lua.  Do you 
have it?

Regards,
Tomás

**Comment by denisdemais** [comment]
Hi.
I'm using a embed version, but, i can develop this binding.

**Comment by tomasguisasola** [comment]
Hi Denis

As I told you, now I can't look at this.  So if you prefer, you can 
write a simple file to fake luasocket's http module and let LuaSOAP 
believe everything is there :-)  This fake module would just call the 
function from another library.

Regards,
Tomás

**Comment by denisdemais** [comment]
tkz
